# Generated by Django 5.2.4 on 2025-07-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='outsideunittype',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Outside Unit Type'),
        ),
    ]
