# Generated by Django 5.2.4 on 2025-07-15 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0002_alter_equipselection_outsideunittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentjobinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
