# Generated by Django 5.2.4 on 2025-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0004_remove_currentjobinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipselection',
            name='optionid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='equipselection',
            name='options',
            field=models.CharField(default=1, max_length=45, verbose_name=''),
            preserve_default=False,
        ),
    ]
