# Generated by Django 5.2.4 on 2025-07-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0005_equipselection_optionid_equipselection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='options',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
