# Generated by Django 5.2.4 on 2025-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0006_alter_equipselection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorinfo',
            name='const',
            field=models.CharField(max_length=15, verbose_name='St:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custst',
            field=models.CharField(max_length=15, null=True, verbose_name='St:'),
        ),
    ]
