# Generated by Django 5.2.4 on 2025-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0007_alter_contractorinfo_const_alter_customerinfo_custst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='optionsid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='options',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
