# Generated by Django 5.2.4 on 2025-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0008_bidding_optionsid_alter_bidding_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('option', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
            ],
        ),
    ]
