# Generated by Django 5.2.4 on 2025-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0009_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaljobcost',
            name='bidid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
