# Generated by Django 5.2.4 on 2025-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0010_totaljobcost_bidid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedEquipB',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type:')),
                ('mfg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg:')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('mfgmodeldescrip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg Descrip.')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('warr', models.CharField(blank=True, max_length=70, null=True, verbose_name="BTU's")),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEquipC',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type:')),
                ('mfg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg:')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('mfgmodeldescrip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg Descrip.')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('warr', models.CharField(blank=True, max_length=70, null=True, verbose_name="BTU's")),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEquipD',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type:')),
                ('mfg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg:')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('mfgmodeldescrip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg Descrip.')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('warr', models.CharField(blank=True, max_length=70, null=True, verbose_name="BTU's")),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEquipE',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type:')),
                ('mfg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg:')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('mfgmodeldescrip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mfg Descrip.')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('warr', models.CharField(blank=True, max_length=70, null=True, verbose_name="BTU's")),
            ],
        ),
    ]
