# Generated by Django 5.2.4 on 2025-09-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0011_selectedequipb_selectedequipc_selectedequipd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedEquipB',
        ),
        migrations.DeleteModel(
            name='SelectedEquipC',
        ),
        migrations.DeleteModel(
            name='SelectedEquipD',
        ),
        migrations.DeleteModel(
            name='SelectedEquipE',
        ),
    ]
