# Generated by Django 5.2.4 on 2025-09-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0012_delete_selectedequipb_delete_selectedequipc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custpagelocation',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('joblocation', models.CharField(blank=True, max_length=45, null=True, verbose_name='Job Location:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
