# Generated by Django 5.2.4 on 2025-09-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0013_custpagelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiformB',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('optionid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('options', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('quanity', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('mfg', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description')),
                ('eff', models.CharField(blank=True, max_length=50, null=True, verbose_name='Efficiency')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='multiformC',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('optionid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('options', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('quanity', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('mfg', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description')),
                ('eff', models.CharField(blank=True, max_length=50, null=True, verbose_name='Efficiency')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='multiformD',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('optionid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('options', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('quanity', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('mfg', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description')),
                ('eff', models.CharField(blank=True, max_length=50, null=True, verbose_name='Efficiency')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='multiformE',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('optionid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('options', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('quanity', models.IntegerField(blank=True, default=None, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('mfg', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='')),
                ('modelnum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model #:')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description')),
                ('eff', models.CharField(blank=True, max_length=50, null=True, verbose_name='Efficiency')),
                ('btu', models.CharField(blank=True, max_length=50, null=True, verbose_name="BTU's")),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
    ]
