# Generated by Django 5.2.4 on 2025-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0014_multiformb_multiformc_multiformd_multiforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentjobinfo',
            name='count',
            field=models.IntegerField(default=None, null=True, verbose_name='JobID.'),
        ),
    ]
