# Generated by Django 5.2.4 on 2025-10-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0015_currentjobinfo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
