# Generated by Django 5.2.4 on 2025-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0017_multiforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedequip',
            name='eff',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Efficiency'),
        ),
        migrations.AddField(
            model_name='selectedequip',
            name='quanity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
