# Generated by Django 5.2.4 on 2025-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0018_selectedequip_eff_selectedequip_quanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedequip',
            name='bidid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
