# Generated by Django 5.2.4 on 2025-10-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0019_selectedequip_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedequip',
            name='equipid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
