# Generated by Django 5.2.4 on 2025-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0020_selectedequip_equipid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('matcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('taxrate', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('totalmatcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('directlaborcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('ohlabor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('totallaborcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('netjobcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('netprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('percenatage', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('targetnetprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('Seasonaldiscount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('costplusprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('subcontractors', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('instantrebate1', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('instantrebate2', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('jobcostprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('rebateamouint', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('finaljobcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
    ]
