# Generated by Django 5.2.4 on 2025-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0022_equipmentcost_laborcost_matcost_osrcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcost',
            name='descript',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='laborcost',
            name='descript',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='matcost',
            name='descript',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='osrcost',
            name='descript',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
