# Generated by Django 5.2.4 on 2025-10-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0023_equipmentcost_descript_laborcost_descript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcost',
            name='descript',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name=''),
        ),
    ]
