# Generated by Django 5.2.4 on 2025-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0027_jobcost_salestax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('netprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('ohlabor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
                ('salestax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
    ]
