# Generated by Django 5.2.4 on 2025-10-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0029_jobcost_netprofitcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='netjobcost2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='netjobcost3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
