# Generated by Django 5.2.4 on 2025-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0031_jobcost_osrcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('netprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
    ]
