from django.urls import path, include
from . import views
from .views import PostsListView
from django.contrib.auth.views import LoginView

app_name = "mhadatabase"
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('mha', LoginView.as_view(template_name='mha/welcome.html'), name='mha'),
    path('main/', views.main, name='main'),
    path('mha/', views.welcome, name='mha'),
    path('', views.PostsListView.as_view(), name='export'),
    #    path('export/', views.PostsListView, name='export'),
    path('installbidingpage/', views.installbidingpage, name='installbidingpage'),
    path('equipmat/', views.equipmat, name='equipmat'),
    path('openequip/', views.openequip, name='openequip'),
    path('addnewequip/', views.addnewequip, name='addnewequip'),
    path('addnewequip2/', views.addnewequip2, name='addnewequip2'),
    path('addnewequip1/', views.addnewequip1, name='addnewequip1'),
    path('model/', views.model, name='model'),
    path('model2/', views.model2, name='model2'),
    #    path('load_model/', views.load_model, name='load_model'),
    path('load_model2/', views.load_model2, name='load_model2'),
    #    path('mfg/', views.mfg, name='mfg'),
    #    path('mfg2/', views.mfg2, name='mfg2'),
    path('load_mfg/', views.load_mfg, name='load_mfg'),
    #    path('load_mfg2/', views.load_mfg2, name='load_mfg2'),
    path('mfg2/', views.mfg2, name='mfg2'),
    path('mfg22/', views.mfg22, name='mfg22'),
    path('load_mfg2/', views.load_mfg2, name='load_mfg2'),
    path('smart/', views.smart, name='smart'),
    #    path('type2/', views.type2, name='type2'),
    #    path('load_type/', views.load_type, name='load_type'),
    #    path('load_type2/', views.load_type2, name='load_type2'),
    path('type2/', views.type2, name='type2'),
    path('type22/', views.type22, name='type22'),
    path('load_type2/', views.load_type2, name='load_type2'),
    path('load_type/', views.load_type, name='load_type'),

    path('config/', views.config, name='config'),
    path('config2/', views.config2, name='config2'),
    path('load_config/', views.load_config, name='load_config'),
    path('load_config2/', views.load_config2, name='load_config2'),

    path('eff/', views.eff, name='eff'),
    path('eff2/', views.eff2, name='eff2'),
    path('load_eff/', views.load_eff, name='load_eff'),
    path('load_eff2/', views.load_eff2, name='load_eff2'),

    path('mfgmodeldescrip/', views.mfgmodeldescrip, name='mfgmodeldescrip'),
    path('mfgmodeldescrip2/', views.mfgmodeldescrip2, name='mfgmodeldescrip2'),
    path('load_mfgmodeldescrip/', views.load_mfgmodeldescrip, name='load_mfgmodeldescrip'),
    path('load_mfgmodeldescrip2/', views.load_mfgmodeldescrip2, name='load_mfgmodeldescrip2'),

    path('gasviv/', views.gasviv, name='gasviv'),
    path('gasviv2/', views.gasviv2, name='gasviv2'),
    path('load_gasviv/', views.load_gasviv, name='load_gasviv'),
    path('load_gasviv2/', views.load_gasviv2, name='load_gasviv2'),

    path('motortype/', views.motortype, name='motortype'),
    path('motortype2/', views.motortype2, name='motortype2'),
    path('load_motortype/', views.load_motortype, name='load_motortype'),
    path('load_motortype2/', views.load_motortype2, name='load_motortype2'),

    path('description/', views.description, name='description'),
    path('description2/', views.description2, name='description2'),
    path('load_description/', views.load_description, name='load_description'),
    path('load_description2/', views.load_description2, name='load_description2'),

    path('refrig/', views.refrig, name='refrig'),
    path('refrig2/', views.refrig2, name='refrig2'),
    path('load_refrig/', views.load_refrig, name='load_refrig'),
    path('load_refrig2/', views.load_refrig2, name='load_refrig2'),

    path('btu/', views.btu, name='btu'),
    path('btu2/', views.btu2, name='btu2'),
    path('load_btu/', views.load_btu, name='load_btu'),
    path('load_btu2/', views.load_btu2, name='load_btu2'),

    path('outputstg1/', views.outputstg1, name='outputstg1'),
    path('outputstg12/', views.outputstg12, name='outputstg12'),
    path('load_outputstg1/', views.load_outputstg1, name='load_outputstg1'),
    path('load_outputstg12/', views.load_outputstg12, name='load_outputstg12'),

    path('outputstg2/', views.outputstg2, name='outputstg2'),
    path('outputstg22/', views.outputstg22, name='outputstg22'),
    path('load_outputstg2/', views.load_outputstg2, name='load_outputstg2'),
    path('load_outputstg22/', views.load_outputstg22, name='load_outputstg22'),

    path('outputstg3/', views.outputstg3, name='outputstg3'),
    path('outputstg32/', views.outputstg32, name='outputstg32'),
    path('load_outputstg3/', views.load_outputstg3, name='load_outputstg3'),
    path('load_outputstg32/', views.load_outputstg32, name='load_outputstg32'),

    path('<path:modelnum>/load_motortypeedit/', views.load_motortypeedit, name='load_motortypeedit'),
    path('<path:modelnum>/load_refrigedit/', views.load_refrigedit, name='load_refrigedit'),

    path('<path:modelnum>/load_btuedit/', views.load_btuedit, name='load_btuedit'),

    path('<path:modelnum>/load_2model/', views.load_2model, name='load_2model'),
    path('<path:modelnum>/load_2config/', views.load_2config, name='load_2config'),
    path('<path:modelnum>/load_2cost/', views.load_2cost, name='load_2cost'),
    path('<path:modelnum>/load_2height/', views.load_2height, name='load_2height'),
    path('<path:modelnum>/load_2width/', views.load_2width, name='load_2width'),
    path('<path:modelnum>/load_2depth/', views.load_2depth, name='load_2depth'),
    path('<path:modelnum>/load_2warr/', views.load_2warr, name='load_2warr'),

    path('<path:id>/costedit/', views.costedit, name='costedit'),
    path('<path:id>/heightedit/', views.heightedit, name='heightedit'),
    path('<path:id>/widthedit/', views.widthedit, name='widthedit'),
    path('<path:id>/depthedit/', views.depthedit, name='depthedit'),
    path('<path:id>/deleteeditequip/', views.deleteeditequip, name='deleteeditequip'),


    path('cost/', views.cost, name='cost'),
    path('costA/', views.costA, name='costA'),
    path('cost2/', views.cost2, name='cost2'),
    path('load_cost/', views.load_cost, name='load_cost'),
    path('load_cost2/', views.load_cost2, name='load_cost2'),
    path('load_cost3/', views.load_cost3, name='load_cost3'),
    path('<path:id>/load_costedit/', views.load_costedit, name='load_costedit'),

    path('<path:id>/load_coilheightedit/', views.load_coilheightedit, name='load_coilheightedit'),
    path('<path:id>/load_coilwidthedit/', views.load_coilwidthedit, name='load_coilwidthedit'),
    path('<path:id>/load_coildepthedit/', views.load_coildepthedit, name='load_coildepthedit'),






    path('<path:modelnum>/warredit/', views.warredit, name='warredit'),
    path('warr/', views.warr, name='warr'),
    path('warrA/', views.warrA, name='warrA'),
    path('warr2/', views.warr2, name='warr2'),
    path('warr3/', views.warr3, name='warr3'),
    path('load_warr/', views.load_warr, name='load_warr'),
    path('load_warr2/', views.load_warr2, name='load_warr2'),
    path('load_addnew/', views.load_addnew, name='load_addnew'),
    path('addnew2/', views.addnew2, name='addnew2'),
    path('height/', views.height, name='height'),
    path('heightA/', views.heightA, name='heightA'),
    path('load_height/', views.load_height, name='load_height'),
    path('load_height2/', views.load_height2, name='load_height2'),
    path('width/', views.width, name='width'),
    path('widthA/', views.widthA, name='widthA'),
    path('load_width/', views.load_width, name='load_width'),
    path('load_width2/', views.load_width2, name='load_width2'),
    path('depth/', views.depth, name='depth'),
    path('depthA/', views.depthA, name='depthA'),
    path('load_depth/', views.load_depth, name='load_depth'),
    path('load_depth2/', views.load_depth2, name='load_depth2'),
    path('deleteequip/', views.deleteequip, name='deleteequip'),
    path('updateequip/', views.updateequip, name='updateequip'),
    path('modequip/', views.modequip, name='modequip'),
    path('typeupdate/', views.typeupdate, name='typeupdate'),
    path('load_typeupdate/', views.load_typeupdate, name='load_typeupdate'),
    path('mfgupdate/', views.mfgupdate, name='mfgupdate'),
    path('modnumupdate/', views.modnumupdate, name='modnumupdate'),
    path('furncoilheight/', views.furncoilheight, name='furncoilheight'),



    path('mfgupdateload/', views.mfgupdateload, name='mfgupdateload'),
    path('load_mfgupdate/', views.load_mfgupdate, name='load_mfgupdate'),
    path('load_mfgupdate2/', views.load_mfgupdate2, name='load_mfgupdate2'),
    path('effupdate/', views.effupdate, name='effupdate'),
    path('effupdateload/', views.effupdateload, name='effupdateload'),
    path('load_efficiencyupdatefurn/', views.load_efficiencyupdatefurn, name='load_efficiencyupdatefurn'),

    path('mfgmodeldescripload/', views.mfgmodeldescripload, name='mfgmodeldescripload'),

    path('efficiencyupdatecond/', views.efficiencyupdatecond, name='efficiencyupdatecond'),
    path('load_efficiencyupdatecond/', views.load_efficiencyupdatecond, name='load_efficiencyupdatecond'),

    path('load_efficiencyupdatefurn2/', views.load_efficiencyupdatefurn2, name='load_efficiencyupdatefurn2'),
    path('load_efficiencyupdatecond2/', views.load_efficiencyupdatecond2, name='load_efficiencyupdatecond2'),
    path('modeldescripupdate/', views.modeldescripupdate, name='modeldescripupdate'),
    path('load_modeldescripupdate/', views.load_modeldescripupdate, name='load_modeldescripupdate'),
    path('load_modeldescripupdate2/', views.load_modeldescripupdate2, name='load_modeldescripupdate2'),

    path('modeldescripupdatecond/', views.modeldescripupdatecond, name='modeldescripupdatecond'),
    path('load_modeldescripupdatecond/', views.load_modeldescripupdatecond, name='load_modeldescripupdatecond'),
    path('load_modeldescripupdatecond2/', views.load_modeldescripupdatecond2, name='load_modeldescripupdatecond2'),

    path('configupdate/', views.configupdate, name='configupdate'),
    path('load_configupdate/', views.load_configupdate, name='load_configupdate'),
    path('update1/', views.update1, name='update1'),
    path('update2/', views.update2, name='update2'),
    path('update3/', views.update3, name='update3'),

    path('update3/', views.update3, name='update3'),

    path('update4/', views.update4, name='update4'),
    path('<path:id>/editquip/', views.editquip, name='editquip'),
    path('<path:modelnum>/editquip2/', views.editquip2, name='editquip2'),
    path('<path:modelnum>/editfurnequip/', views.editfurnequip, name='editfurnequip'),
    #    path('furnglobalincrease1/', views.furnglobalincrease1, name='furnglobalincrease1'),
    path('globalincrease1/', views.furnglobalincrease1, name='furnglobalincrease1'),
    path('globalincrease2/', views.globalincrease2, name='globalincrease2'),
    path('globalincrease3/', views.globalincrease3, name='globalincrease3'),
    path('globalincrease4/', views.globalincrease4, name='globalincrease4'),
    path('globalincrease5/', views.globalincrease5, name='globalincrease5'),
    path('percentincrease1/', views.percentincrease1, name='percentincrease1'),
    path('percentincrease2/', views.percentincrease2, name='percentincrease2'),
    path('percentincrease3/', views.percentincrease3, name='percentincrease3'),
    path('percentincrease4/', views.percentincrease4, name='percentincrease4'),
    path('percentincrease5/', views.percentincrease5, name='percentincrease5'),
    path('updateprice1/', views.updateprice1, name='updateprice1'),
    path('updateprice2/', views.updateprice2, name='updateprice2'),
    path('updateprice3/', views.updateprice3, name='updateprice3'),
    path('updateprice4/', views.updateprice4, name='updateprice4'),
    path('updateprice5/', views.updateprice5, name='updateprice5'),
    path('mattoupdate/', views.mattoupdate, name='mattoupdate'),
    path('addnewmat/', views.addnewmat, name='addnewmat'),
    path('adddescrip/', views.adddescrip, name='adddescrip'),
    path('cost/', views.cost, name='cost'),
    path('addcost/', views.addcost, name='addcost'),
    path('addmatmfg/', views.addmatmfg, name='addmatmfg'),
    path('matmfg2/', views.matmfg2, name='matmfg2'),
    path('load_matmfg2/', views.load_matmfg2, name='load_matmfg2'),
    path('matvendor/', views.matvendor, name='matvendor'),
    path('matvendor2/', views.matvendor2, name='matvendor2'),
    path('load_matvendor2/', views.load_matvendor2, name='load_matvendor2'),
    path('vendornum/', views.vendornum, name='vendornum'),
    path('mattype/', views.mattype, name='mattype'),
    path('mattype2/', views.mattype2, name='mattype2'),
    path('load_mattype2/', views.load_mattype2, name='load_mattype2'),
    path('deletemat/', views.deletemat, name='deletemat'),
    path('<int:idA>/deletemat1/', views.deletemat1, name='deletemat1'),
    path('matsearch/', views.matsearch, name='matsearch'),
    path('filtermfg/', views.filtermfg, name='filtermfg'),
    path('filtervendor/', views.filtervendor, name='filtervendor'),
    path('filtertype/', views.filtertype, name='filtertype'),
    path('mfgsearch/', views.mfgsearch, name='mfgsearch'),
    path('vendorsearch/', views.vendorsearch, name='vendorsearch'),
    path('typesearch/', views.typesearch, name='typesearch'),
    path('<int:idA>/editmat/', views.editmat, name='editmat'),
    path('<int:idA>/costmat/', views.costmat, name='costmat'),
    path('<int:idA>/matcostload/', views.matcostload, name='matcostload'),
    path('<int:idA>/mfgmat/', views.mfgmat, name='mfgmat'),
    path('<int:idA>/matmfgload/', views.matmfgload, name='matmfgload'),
    path('<int:idA>/mfgvendor/', views.mfgvendor, name='mfgvendor'),
    path('<int:idA>/matvendorload/', views.matvendorload, name='matvendorload'),
    path('<int:idA>/mfgvennum/', views.mfgvennum, name='mfgvennum'),
    path('<int:idA>/matvennumload/', views.matvennumload, name='matvennumload'),
    path('<int:idA>/mfgtype/', views.mfgtype, name='mfgtype'),
    path('<int:idA>/mattypeload/', views.mattypeload, name='mattypeload'),
    path('customer/', views.customer, name='customer'),
    path('newcon/', views.newcon, name='newcon'),
    path('conerror', views.conerror, name='conerror'),
    path('custerror', views.custerror, name='custerror'),
    path('<int:id>/dupconinfo/', views.dupconinfo, name='dupconinfo'),
    path('<int:id>/newcust/', views.newcust, name='newcust'),
    path('<int:id>/jobselection/', views.jobselection, name='jobselection'),
    path('<int:id>/jobselection2/', views.jobselection2, name='jobselection2'),
    path('<int:bidid>/jobselection3/', views.jobselection3, name='jobselection3'),
    path('<int:bidid>/jobselection4/', views.jobselection4, name='jobselection4'),
    path('<int:bidid>/jobselection5/', views.jobselection5, name='jobselection5'),
    path('<int:id>/contractorpage/', views.contractorpage, name='contractorpage'),
    path('<int:custid>/customerinfo/', views.customerinfo, name='customerinfo'),
    path('<int:id>/customerpage/', views.customerpage, name='customerpage'),
    path('<int:id>/addcust/', views.addcust, name='addcust'),
    path('<int:id>/conedit/', views.conedit, name='conedit'),
    path('<int:id>/custedit/', views.custedit, name='custedit'),
    path('<int:custid>/yesdupcon/', views.yesdupcon, name='yesdupcon'),
    path('con_info_existing', views.con_info_existing, name='con_info_existing'),
    path('cust_info_existing', views.cust_info_existing, name='cust_info_existing'),
    path('custcompany', views.custcompany, name='custcompany'),
    path('<int:id>/addcustconfirm/', views.addcustconfirm, name='addcustconfirm'),
    path('<int:id>/addnewcust/', views.addnewcust, name='addnewcust'),
    path('<int:id>/equipselection1/', views.equipselection1, name='equipselection1'),
    path('<int:id>/equipselection2/', views.equipselection2, name='equipselection2'),
    path('joblocation', views.joblocation, name='joblocation'),
    path('airhandler', views.airhandler, name='airhandler'),
    path('outsideunit', views.outsideunit, name='outsideunit'),
    path('load_condeff', views.load_condeff, name='load_condeff'),
    path('condeff', views.condeff, name='condeff'),
    path('load_condbtu', views.load_condbtu, name='load_condbtu'),
    path('condbtu', views.condbtu, name='condbtu'),
    path('load_conddescript', views.load_conddescript, name='load_conddescript'),
    path('conddescrip', views.conddescrip, name='conddescrip'),
    path('load_condmodnum', views.load_condmodnum, name='load_condmodnum'),
    path('condmodnum', views.condmodnum, name='condmodnum'),
    path('load_furnbtu', views.load_furnbtu, name='load_furnbtu'),
    path('furnbtu', views.furnbtu, name='furnbtu'),
    path('load_furnconfig', views.load_furnconfig, name='load_furnconfig'),
    path('furnconfig', views.furnconfig, name='furnconfig'),
    path('load_furneff', views.load_furneff, name='load_furneff'),
    path('furneff', views.furneff, name='furneff'),
    path('load_furndescript', views.load_furndescript, name='load_furndescript'),
    path('furndescript', views.furndescript, name='furndescript'),
    path('load_furnmodnum', views.load_furnmodnum, name='load_furnmodnum'),
    path('furnmodnum', views.furnmodnum, name='furnmodnum'),
    path('furnmodnum2', views.furnmodnum2, name='furnmodnum2'),
    path('load_thermomfg', views.load_thermomfg, name='load_thermomfg'),
    path('thermomfg', views.thermomfg, name='thermomfg'),
    path('load_thermomodnum', views.load_thermomodnum, name='load_thermomodnum'),
    path('thermostatmodnum', views.thermostatmodnum, name='thermostatmodnum'),
    path('load_furnheight', views.load_furnheight, name='load_furnheight'),
    path('load_furnwidth', views.load_furnwidth, name='load_furnwidth'),
    path('coiltype', views.coiltype, name='coiltype'),
    path('load_coilbtu', views.load_coilbtu, name='load_coilbtu'),
    path('coilbtu', views.coilbtu, name='coilbtu'),
    path('load_coilconfig', views.load_coilconfig, name='load_coilconfig'),
    path('coilconfig', views.coilconfig, name='coilconfig'),
    path('load_coilmodnum', views.load_coilmodnum, name='load_coilmodnum'),
    path('coilmodnum', views.coilmodnum, name='coilmodnum'),
    path('load_coilheight', views.load_coilheight, name='load_coilheight'),
    path('load_coilwidth', views.load_coilwidth, name='load_coilwidth'),
    path('load_furncoilheight', views.load_furncoilheight, name='load_furncoilheight'),
    path('load_coiltype', views.load_coiltype, name='load_coiltype'),
    path('<path:id>/deleteediteequip/', views.deleteediteequip, name='deleteediteequip'),
    path('load_vendor1', views.load_vendor1, name='load_vendor1'),
    path('load_vendor2', views.load_vendor2, name='load_vendor2'),
    path('load_totalrebate', views.load_totalrebate, name='load_totalrebate'),
    path('deleteequipselection', views.deleteequipselection, name='deleteequipselection'),

    path('<int:bidid>/bidpage/', views.bidpage, name='bidpage'),
    path('<int:bidid>/jobcost/', views.jobcost, name='jobcost'),
    path('<int:jobid>/cancelbid/', views.cancelbid, name='cancelbid'),


    path('<int:jobid>/addnewosr/', views.addnewosr, name='addnewosr'),
    path('<int:jobid>/newvendordescript/', views.newvendordescript, name='newvendordescript'),
    path('<int:jobid>/newvendorprice/', views.newvendorprice, name='newvendorprice'),
    path('<int:jobid>/newvendor/', views.newvendor, name='newvendor'),
    path('<int:jobid>/deletenewvendor/', views.deletenewvendor, name='deletenewvendor'),

    path('<int:jobid>/load_quanity1/', views.load_quanity1, name='load_quanity1'),
    path('<int:bidid>/quan1/', views.quan1, name='quan1'),
    path('<int:bidid>/quan2/', views.quan2, name='quan2'),
    path('<int:bidid>/quan3/', views.quan3, name='quan3'),
    path('<int:bidid>/quan4/', views.quan4, name='quan4'),
    path('<int:bidid>/quan5/', views.quan5, name='quan5'),
    path('<int:bidid>/quan6/', views.quan6, name='quan6'),
    path('<int:bidid>/quan7/', views.quan7, name='quan7'),

    path('<int:bidid>/load_jobtype1/', views.load_jobtype1, name='load_jobtype1'),
    path('<int:bidid>/load_jobtype2/', views.load_jobtype2, name='load_jobtype2'),
    path('<int:bidid>/load_jobtype3/', views.load_jobtype3, name='load_jobtype3'),
    path('<int:bidid>/load_jobtype4/', views.load_jobtype4, name='load_jobtype4'),
    path('<int:bidid>/jobtype5/', views.jobtype5, name='jobtype5'),
    path('<int:bidid>/jobtype6/', views.jobtype6, name='jobtype6'),
    path('<int:bidid>/jobtype7/', views.jobtype7, name='jobtype7'),
    path('<int:bidid>/load_descrip1/', views.load_descrip1, name='load_descrip1'),
    path('<int:bidid>/load_descrip2/', views.load_descrip2, name='load_descrip2'),
    path('<int:bidid>/load_descrip3/', views.load_descrip3, name='load_descrip3'),
    path('<int:bidid>/load_descrip4/', views.load_descrip4, name='load_descrip4'),

    path('<int:bidid>/jobdescrip5/', views.jobdescrip5, name='jobdescrip5'),
    path('<int:bidid>/load_jobtype5/', views.load_jobtype5, name='load_jobtype5'),
    path('<int:bidid>/load_jobtype5b/', views.load_jobtype5b, name='load_jobtype5b'),
    path('<int:bidid>/load_jobdescrip5/', views.load_jobdescrip5, name='load_jobdescrip5'),
    path('<int:bidid>/load_jobdescrip5b/', views.load_jobdescrip5, name='load_jobdescrip5'),
    path('<int:bidid>/delete5/', views.delete5, name='delete5'),
    path('<int:bidid>/load_quanity5/', views.load_quanity5, name='load_quanity5'),

    path('<int:bidid>/jobdescrip6/', views.jobdescrip6, name='jobdescrip6'),
    path('<int:bidid>/load_jobtype6/', views.load_jobtype6, name='load_jobtype6'),
    path('<int:bidid>/load_jobtype6b/', views.load_jobtype6b, name='load_jobtype6b'),
    path('<int:bidid>/load_jobdescrip6/', views.load_jobdescrip6, name='load_jobdescrip6'),
    path('<int:bidid>/load_jobdescrip6b/', views.load_jobdescrip6, name='load_jobdescrip6'),
    path('<int:bidid>/delete6/', views.delete6, name='delete6'),
    path('<int:bidid>/load_quanity6/', views.load_quanity6, name='load_quanity6'),

    path('<int:bidid>/jobdescrip7/', views.jobdescrip7, name='jobdescrip7'),
    path('<int:bidid>/load_jobtype7/', views.load_jobtype7, name='load_jobtype7'),
    path('<int:bidid>/load_jobtype7b/', views.load_jobtype7b, name='load_jobtype7b'),
    path('<int:bidid>/load_jobdescrip7/', views.load_jobdescrip7, name='load_jobdescrip7'),
    path('<int:bidid>/load_jobdescrip7b/', views.load_jobdescrip7, name='load_jobdescrip7'),
    path('<int:bidid>/delete7/', views.delete7, name='delete7'),
    path('<int:bidid>/load_quanity7/', views.load_quanity7, name='load_quanity7'),

    path('<int:bidid>/descript8/', views.descript8, name='descript8'),
    path('<int:bidid>/load_descript8/', views.load_descript8, name='load_descript8'),
    path('<int:bidid>/load_descript8b/', views.load_descript8b, name='load_descript8b'),
    path('<int:bidid>/load_quanity8/', views.load_quanity8, name='load_quanity8'),
    path('<int:bidid>/quant8/', views.quant8, name='quant8'),
    path('<int:bidid>/delete8/', views.delete8, name='delete8'),

    path('<int:bidid>/descript9/', views.descript9, name='descript9'),
    path('<int:bidid>/load_descript9/', views.load_descript9, name='load_descript9'),
    path('<int:bidid>/load_descript9b/', views.load_descript9b, name='load_descript9b'),
    path('<int:bidid>/load_quanity9/', views.load_quanity9, name='load_quanity9'),
    path('<int:bidid>/quant9/', views.quant9, name='quant9'),
    path('<int:bidid>/delete9/', views.delete9, name='delete9'),

    path('<int:bidid>/descript10/', views.descript10, name='descript10'),
    path('<int:bidid>/load_descript10/', views.load_descript10, name='load_descript10'),
    path('<int:bidid>/load_descript10b/', views.load_descript10b, name='load_descript10b'),
    path('<int:bidid>/load_quanity10/', views.load_quanity10, name='load_quanity10'),
    path('<int:bidid>/quant10/', views.quant10, name='quant10'),
    path('<int:bidid>/delete10/', views.delete10, name='delete10'),

    path('<int:bidid>/descript11/', views.descript11, name='descript11'),
    path('<int:bidid>/load_descript11/', views.load_descript11, name='load_descript11'),
    path('<int:bidid>/load_descript11b/', views.load_descript11b, name='load_descript11b'),
    path('<int:bidid>/load_quanity11/', views.load_quanity11, name='load_quanity11'),
    path('<int:bidid>/quant11/', views.quant11, name='quant11'),
    path('<int:bidid>/delete11/', views.delete11, name='delete11'),

    path('<int:bidid>/descript12/', views.descript12, name='descript12'),
    path('<int:bidid>/load_descript12/', views.load_descript12, name='load_descript12'),
    path('<int:bidid>/load_descript12b/', views.load_descript12b, name='load_descript12b'),
    path('<int:bidid>/load_quanity12/', views.load_quanity12, name='load_quanity12'),
    path('<int:bidid>/quant12/', views.quant12, name='quant12'),
    path('<int:bidid>/delete12/', views.delete12, name='delete12'),

    path('<int:bidid>/descript13/', views.descript13, name='descript13'),
    path('<int:bidid>/load_descript13/', views.load_descript13, name='load_descript13'),
    path('<int:bidid>/load_descript13b/', views.load_descript13b, name='load_descript13b'),
    path('<int:bidid>/load_quanity13/', views.load_quanity13, name='load_quanity13'),
    path('<int:bidid>/quant13/', views.quant13, name='quant13'),
    path('<int:bidid>/delete13/', views.delete13, name='delete13'),

    path('<int:bidid>/descript14/', views.descript14, name='descript14'),
    path('<int:bidid>/load_descript14/', views.load_descript14, name='load_descript14'),
    path('<int:bidid>/load_descript14b/', views.load_descript14b, name='load_descript14b'),
    path('<int:bidid>/load_quanity14/', views.load_quanity14, name='load_quanity14'),
    path('<int:bidid>/quant14/', views.quant14, name='quant14'),
    path('<int:bidid>/delete14/', views.delete14, name='delete14'),

    path('<int:bidid>/descript15/', views.descript15, name='descript15'),
    path('<int:bidid>/load_descript15/', views.load_descript15, name='load_descript15'),
    path('<int:bidid>/load_descript15b/', views.load_descript15b, name='load_descript15b'),
    path('<int:bidid>/load_quanity15/', views.load_quanity15, name='load_quanity15'),
    path('<int:bidid>/quant15/', views.quant15, name='quant15'),
    path('<int:bidid>/delete15/', views.delete15, name='delete15'),

    path('<int:bidid>/descript16/', views.descript16, name='descript16'),
    path('<int:bidid>/load_descript16/', views.load_descript16, name='load_descript16'),
    path('<int:bidid>/load_descript16b/', views.load_descript16b, name='load_descript16b'),
    path('<int:bidid>/load_quanity16/', views.load_quanity16, name='load_quanity16'),
    path('<int:bidid>/quant16/', views.quant16, name='quant16'),
    path('<int:bidid>/delete16/', views.delete16, name='delete16'),

    path('<int:bidid>/descript17/', views.descript17, name='descript17'),
    path('<int:bidid>/load_descript17/', views.load_descript17, name='load_descript17'),
    path('<int:bidid>/load_descript17b/', views.load_descript17b, name='load_descript17b'),
    path('<int:bidid>/load_quanity17/', views.load_quanity17, name='load_quanity17'),
    path('<int:bidid>/quant17/', views.quant17, name='quant17'),
    path('<int:bidid>/delete17/', views.delete17, name='delete17'),

    path('<int:bidid>/descript18/', views.descript18, name='descript18'),
    path('<int:bidid>/load_descript18/', views.load_descript18, name='load_descript18'),
    path('<int:bidid>/load_descript18b/', views.load_descript18b, name='load_descript18b'),
    path('<int:bidid>/load_quanity18/', views.load_quanity18, name='load_quanity18'),
    path('<int:bidid>/quant18/', views.quant18, name='quant18'),
    path('<int:bidid>/delete18/', views.delete18, name='delete18'),

    path('<int:bidid>/descript19/', views.descript19, name='descript19'),
    path('<int:bidid>/load_descript19/', views.load_descript19, name='load_descript19'),
    path('<int:bidid>/load_descript19b/', views.load_descript19b, name='load_descript19b'),
    path('<int:bidid>/load_quanity19/', views.load_quanity19, name='load_quanity19'),
    path('<int:bidid>/quant19/', views.quant19, name='quant19'),
    path('<int:bidid>/delete19/', views.delete19, name='delete19'),

    path('<int:bidid>/descript20/', views.descript20, name='descript20'),
    path('<int:bidid>/load_descript20/', views.load_descript20, name='load_descript20'),
    path('<int:bidid>/load_descript20b/', views.load_descript20b, name='load_descript20b'),
    path('<int:bidid>/load_quanity20/', views.load_quanity20, name='load_quanity20'),
    path('<int:bidid>/quant20/', views.quant20, name='quant20'),
    path('<int:bidid>/delete20/', views.delete20, name='delete20'),

    path('<int:bidid>/descript21/', views.descript21, name='descript21'),
    path('<int:bidid>/load_descript21/', views.load_descript21, name='load_descript21'),
    path('<int:bidid>/load_descript21b/', views.load_descript21b, name='load_descript21b'),
    path('<int:bidid>/load_quanity21/', views.load_quanity21, name='load_quanity21'),
    path('<int:bidid>/quant21/', views.quant21, name='quant21'),
    path('<int:bidid>/delete21/', views.delete21, name='delete21'),

    path('<int:bidid>/descript22/', views.descript22, name='descript22'),
    path('<int:bidid>/load_descript22/', views.load_descript22, name='load_descript22'),
    path('<int:bidid>/load_descript22b/', views.load_descript22b, name='load_descript22b'),
    path('<int:bidid>/load_quanity22/', views.load_quanity22, name='load_quanity22'),
    path('<int:bidid>/quant22/', views.quant22, name='quant22'),
    path('<int:bidid>/delete22/', views.delete22, name='delete22'),

    path('<int:bidid>/descript23/', views.descript23, name='descript23'),
    path('<int:bidid>/load_descript23/', views.load_descript23, name='load_descript23'),
    path('<int:bidid>/load_descript23b/', views.load_descript23b, name='load_descript23b'),
    path('<int:bidid>/load_quanity23/', views.load_quanity23, name='load_quanity23'),
    path('<int:bidid>/quant23/', views.quant23, name='quant23'),
    path('<int:bidid>/delete23/', views.delete23, name='delete23'),

    path('<int:bidid>/descript24/', views.descript24, name='descript24'),
    path('<int:bidid>/load_descript24/', views.load_descript24, name='load_descript24'),
    path('<int:bidid>/load_descript24b/', views.load_descript24b, name='load_descript24b'),
    path('<int:bidid>/load_quanity24/', views.load_quanity24, name='load_quanity24'),
    path('<int:bidid>/quant24/', views.quant24, name='quant24'),
    path('<int:bidid>/delete24/', views.delete24, name='delete24'),

    path('<int:bidid>/descript25/', views.descript25, name='descript25'),
    path('<int:bidid>/load_descript25/', views.load_descript25, name='load_descript25'),
    path('<int:bidid>/load_descript25b/', views.load_descript25b, name='load_descript25b'),
    path('<int:bidid>/load_quanity25/', views.load_quanity25, name='load_quanity25'),
    path('<int:bidid>/quant25/', views.quant25, name='quant25'),
    path('<int:bidid>/delete25/', views.delete25, name='delete25'),

    path('<int:bidid>/descript26/', views.descript26, name='descript26'),
    path('<int:bidid>/load_descript26/', views.load_descript26, name='load_descript26'),
    path('<int:bidid>/load_descript26b/', views.load_descript26b, name='load_descript26b'),
    path('<int:bidid>/load_quanity26/', views.load_quanity26, name='load_quanity26'),
    path('<int:bidid>/quant26/', views.quant26, name='quant26'),
    path('<int:bidid>/delete26/', views.delete26, name='delete26'),

    path('<int:bidid>/descript27/', views.descript27, name='descript27'),
    path('<int:bidid>/load_descript27/', views.load_descript27, name='load_descript27'),
    path('<int:bidid>/load_descript27b/', views.load_descript27b, name='load_descript27b'),
    path('<int:bidid>/load_quanity27/', views.load_quanity27, name='load_quanity27'),
    path('<int:bidid>/quant27/', views.quant27, name='quant27'),
    path('<int:bidid>/delete27/', views.delete27, name='delete27'),

    path('<int:bidid>/descript28/', views.descript28, name='descript28'),
    path('<int:bidid>/load_descript28/', views.load_descript28, name='load_descript28'),
    path('<int:bidid>/load_descript28b/', views.load_descript28b, name='load_descript28b'),
    path('<int:bidid>/load_quanity28/', views.load_quanity28, name='load_quanity28'),
    path('<int:bidid>/quant28/', views.quant28, name='quant28'),
    path('<int:bidid>/delete28/', views.delete28, name='delete28'),

    path('<int:bidid>/descript29/', views.descript29, name='descript29'),
    path('<int:bidid>/load_descript29/', views.load_descript29, name='load_descript29'),
    path('<int:bidid>/load_descript29b/', views.load_descript29b, name='load_descript29b'),
    path('<int:bidid>/load_quanity29/', views.load_quanity29, name='load_quanity29'),
    path('<int:bidid>/quant29/', views.quant29, name='quant29'),
    path('<int:bidid>/delete29/', views.delete29, name='delete29'),

    path('<int:bidid>/descript30/', views.descript30, name='descript30'),
    path('<int:bidid>/load_descript30/', views.load_descript30, name='load_descript30'),
    path('<int:bidid>/load_descript30b/', views.load_descript30b, name='load_descript30b'),
    path('<int:bidid>/load_quanity30/', views.load_quanity30, name='load_quanity30'),
    path('<int:bidid>/quant30/', views.quant30, name='quant30'),
    path('<int:bidid>/delete30/', views.delete30, name='delete30'),

    path('<int:bidid>/descript31/', views.descript31, name='descript31'),
    path('<int:bidid>/load_descript31/', views.load_descript31, name='load_descript31'),
    path('<int:bidid>/load_descript31b/', views.load_descript31b, name='load_descript31b'),
    path('<int:bidid>/load_quanity31/', views.load_quanity31, name='load_quanity31'),
    path('<int:bidid>/quant31/', views.quant31, name='quant31'),
    path('<int:bidid>/delete31/', views.delete31, name='delete31'),

    path('<int:bidid>/descript32/', views.descript32, name='descript32'),
    path('<int:bidid>/load_descript32/', views.load_descript32, name='load_descript32'),
    path('<int:bidid>/load_descript32b/', views.load_descript32b, name='load_descript32b'),
    path('<int:bidid>/load_quanity32/', views.load_quanity32, name='load_quanity32'),
    path('<int:bidid>/quant32/', views.quant32, name='quant32'),
    path('<int:bidid>/delete32/', views.delete32, name='delete32'),

    path('<int:bidid>/descript33/', views.descript33, name='descript33'),
    path('<int:bidid>/load_descript33/', views.load_descript33, name='load_descript33'),
    path('<int:bidid>/load_descript33b/', views.load_descript33b, name='load_descript33b'),
    path('<int:bidid>/load_quanity33/', views.load_quanity33, name='load_quanity33'),
    path('<int:bidid>/quant33/', views.quant33, name='quant33'),
    path('<int:bidid>/delete33/', views.delete33, name='delete33'),

    path('<int:bidid>/descript34/', views.descript34, name='descript34'),
    path('<int:bidid>/load_descript34/', views.load_descript34, name='load_descript34'),
    path('<int:bidid>/load_descript34b/', views.load_descript34b, name='load_descript34b'),
    path('<int:bidid>/load_quanity34/', views.load_quanity34, name='load_quanity34'),
    path('<int:bidid>/quant34/', views.quant34, name='quant34'),
    path('<int:bidid>/delete34/', views.delete34, name='delete34'),

    path('<int:bidid>/descript35/', views.descript35, name='descript35'),
    path('<int:bidid>/load_descript35/', views.load_descript35, name='load_descript35'),
    path('<int:bidid>/load_descript35b/', views.load_descript35b, name='load_descript35b'),
    path('<int:bidid>/load_quanity35/', views.load_quanity35, name='load_quanity35'),
    path('<int:bidid>/quant35/', views.quant35, name='quant35'),
    path('<int:bidid>/delete35/', views.delete35, name='delete35'),

    path('<int:bidid>/descript36/', views.descript36, name='descript36'),
    path('<int:bidid>/load_descript36/', views.load_descript36, name='load_descript36'),
    path('<int:bidid>/load_descript36b/', views.load_descript36b, name='load_descript36b'),
    path('<int:bidid>/load_quanity36/', views.load_quanity36, name='load_quanity36'),
    path('<int:bidid>/quant36/', views.quant36, name='quant36'),
    path('<int:bidid>/delete36/', views.delete36, name='delete36'),

    path('<int:bidid>/descript37/', views.descript37, name='descript37'),
    path('<int:bidid>/load_descript37/', views.load_descript37, name='load_descript37'),
    path('<int:bidid>/load_descript37b/', views.load_descript37b, name='load_descript37b'),
    path('<int:bidid>/load_quanity37/', views.load_quanity37, name='load_quanity37'),
    path('<int:bidid>/quant37/', views.quant37, name='quant37'),
    path('<int:bidid>/delete37/', views.delete37, name='delete37'),

    path('<int:bidid>/descript38/', views.descript38, name='descript38'),
    path('<int:bidid>/load_descript38/', views.load_descript38, name='load_descript38'),
    path('<int:bidid>/load_descript38b/', views.load_descript38b, name='load_descript38b'),
    path('<int:bidid>/load_quanity38/', views.load_quanity38, name='load_quanity38'),
    path('<int:bidid>/quant38/', views.quant38, name='quant38'),
    path('<int:bidid>/delete38/', views.delete38, name='delete38'),

    path('<int:bidid>/descript39/', views.descript39, name='descript39'),
    path('<int:bidid>/load_descript39/', views.load_descript39, name='load_descript39'),
    path('<int:bidid>/load_descript39b/', views.load_descript39b, name='load_descript39b'),
    path('<int:bidid>/load_quanity39/', views.load_quanity39, name='load_quanity39'),
    path('<int:bidid>/quant39/', views.quant39, name='quant39'),
    path('<int:bidid>/delete39/', views.delete39, name='delete39'),

    path('<int:bidid>/descript46/', views.descript46, name='descript46'),
    path('<int:bidid>/load_descript46/', views.load_descript46, name='load_descript46'),
    path('<int:bidid>/load_descript46b/', views.load_descript46b, name='load_descript46b'),
    path('<int:bidid>/load_quanity46/', views.load_quanity46, name='load_quanity46'),
    path('<int:bidid>/quant46/', views.quant46, name='quant46'),
    path('<int:bidid>/delete46/', views.delete46, name='delete46'),

    path('<int:bidid>/quan40/', views.quan40, name='quan40'),
    path('<int:bidid>/delete40/', views.delete40, name='delete40'),
    path('<int:bidid>/descrip40/', views.descrip40, name='descrip40'),
    path('<int:bidid>/descrip40b/', views.descrip40b, name='descrip40b'),
    path('<int:bidid>/load_descript40/', views.load_descript40, name='load_descript40'),
    path('<int:bidid>/load_descript40b/', views.load_descript40b, name='load_descript40b'),
    path('<int:bidid>/load_quanity40/', views.load_quanity40, name='load_quanity40'),

    path('<int:bidid>/quan41/', views.quan41, name='quan41'),
    path('<int:bidid>/delete41/', views.delete41, name='delete41'),
    path('<int:bidid>/descrip41/', views.descrip41, name='descrip41'),
    path('<int:bidid>/descrip41b/', views.descrip41b, name='descrip41b'),
    path('<int:bidid>/load_descript41/', views.load_descript41, name='load_descript41'),
    path('<int:bidid>/load_descript41b/', views.load_descript41b, name='load_descript41b'),
    path('<int:bidid>/load_quanity41/', views.load_quanity41, name='load_quanity41'),

    path('<int:bidid>/quan42/', views.quan42, name='quan42'),
    path('<int:bidid>/delete42/', views.delete42, name='delete42'),
    path('<int:bidid>/descrip42/', views.descrip42, name='descrip42'),
    path('<int:bidid>/descrip42b/', views.descrip42b, name='descrip42b'),
    path('<int:bidid>/load_descript42/', views.load_descript42, name='load_descript42'),
    path('<int:bidid>/load_descript42b/', views.load_descript42b, name='load_descript42b'),
    path('<int:bidid>/load_quanity42/', views.load_quanity42, name='load_quanity42'),

    path('<int:bidid>/quan43/', views.quan43, name='quan43'),
    path('<int:bidid>/delete43/', views.delete43, name='delete43'),
    path('<int:bidid>/descrip43/', views.descrip43, name='descrip43'),
    path('<int:bidid>/descrip43b/', views.descrip43b, name='descrip43b'),
    path('<int:bidid>/load_descript43/', views.load_descript43, name='load_descript43'),
    path('<int:bidid>/load_descript43b/', views.load_descript43b, name='load_descript43b'),
    path('<int:bidid>/load_quanity43/', views.load_quanity43, name='load_quanity43'),

    path('<int:bidid>/quan44/', views.quan44, name='quan44'),
    path('<int:bidid>/delete44/', views.delete44, name='delete44'),
    path('<int:bidid>/descrip44/', views.descrip44, name='descrip44'),
    path('<int:bidid>/descrip44b/', views.descrip44b, name='descrip44b'),
    path('<int:bidid>/load_descript44/', views.load_descript44, name='load_descript44'),
    path('<int:bidid>/load_descript44b/', views.load_descript44b, name='load_descript44b'),
    path('<int:bidid>/load_quanity44/', views.load_quanity44, name='load_quanity44'),

    path('<int:bidid>/quan45/', views.quan45, name='quan45'),
    path('<int:bidid>/delete45/', views.delete45, name='delete45'),
    path('<int:bidid>/descrip45/', views.descrip45, name='descrip45'),
    path('<int:bidid>/descrip45b/', views.descrip45b, name='descrip45b'),
    path('<int:bidid>/load_descript45/', views.load_descript45, name='load_descript45'),
    path('<int:bidid>/load_descript45b/', views.load_descript45b, name='load_descript45b'),
    path('<int:bidid>/load_quanity45/', views.load_quanity45, name='load_quanity45'),

    path('<int:bidid>/materialtype/', views.materialtype, name='materialtype'),

    path('<int:bidid>/techlevel/', views.techlevel, name='techlevel'),
    path('<int:bidid>/techlevelhrs/', views.techlevelhrs, name='techlevelhrs'),

    path('<int:bidid>/techlevel2/', views.techlevel2, name='techlevel2'),
    path('<int:bidid>/techlevelhrs2/', views.techlevelhrs2, name='techlevelhrs2'),

    path('<int:bidid>/techlevel3/', views.techlevel3, name='techlevel3'),
    path('<int:bidid>/techlevelhrs3/', views.techlevelhrs3, name='techlevelhrs3'),

    path('<int:bidid>/techlevel4/', views.techlevel4, name='techlevel4'),
    path('<int:bidid>/techlevelhrs4/', views.techlevelhrs4, name='techlevelhrs4'),


    path('mainsettingpage/', views.mainsettingpage, name='mainsettingpage'),

    path('packagepage1/', views.packagepage1, name='packagepage1'),
    path('package1/', views.package1, name='package1'),
    path('package1a/', views.package1a, name='package1a'),
    path('package1b/', views.package1b, name='package1b'),
    path('package1add/', views.package1add, name='package1add'),
    path('<int:id>/deletepackage1/', views.deletepackage1, name='deletepackage1'),
    path('<int:id>/deletepackage1a/', views.deletepackage1a, name='deletepackage1a'),

    path('packagepage2/', views.packagepage2, name='packagepage2'),
    path('package2/', views.package2, name='package2'),
    path('package2a/', views.package2a, name='package2a'),
    path('package2b/', views.package2b, name='package2b'),
    path('package2add/', views.package2add, name='package2add'),
    path('<int:id>/deletepackage2/', views.deletepackage2, name='deletepackage2'),
    path('<int:id>/deletepackage2a/', views.deletepackage2a, name='deletepackage2a'),

    path('packagepage3/', views.packagepage3, name='packagepage3'),
    path('package3/', views.package3, name='package3'),
    path('package3a/', views.package3a, name='package3a'),
    path('package3b/', views.package3b, name='package3b'),
    path('package3add/', views.package3add, name='package3add'),
    path('<int:id>/deletepackage3/', views.deletepackage3, name='deletepackage3'),
    path('<int:id>/deletepackage3a/', views.deletepackage3a, name='deletepackage3a'),

    path('packagepage4/', views.packagepage4, name='packagepage4'),
    path('package4/', views.package4, name='package4'),
    path('package4a/', views.package4a, name='package4a'),
    path('package4b/', views.package4b, name='package4b'),
    path('package4add/', views.package4add, name='package4add'),
    path('<int:id>/deletepackage4/', views.deletepackage4, name='deletepackage4'),
    path('<int:id>/deletepackage4a/', views.deletepackage4a, name='deletepackage4a'),


    path('package5/', views.package5, name='package5'),
    path('package5a/', views.package5a, name='package5a'),
    path('package5b/', views.package5b, name='package5b'),
    path('package5add/', views.package5add, name='package5add'),
    path('<int:id>/deletepackage5/', views.deletepackage5, name='deletepackage5'),
    path('<int:id>/deletepackage5a/', views.deletepackage5a, name='deletepackage5a'),


    path('package6/', views.package6, name='package6'),
    path('package6a/', views.package6a, name='package6a'),
    path('package6b/', views.package6b, name='package6b'),
    path('package6add/', views.package6add, name='package6add'),
    path('<int:id>/deletepackage6/', views.deletepackage6, name='deletepackage6'),
    path('<int:id>/deletepackage6a/', views.deletepackage6a, name='deletepackage6a'),


    path('package7/', views.package7, name='package7'),
    path('package7a/', views.package7a, name='package7a'),
    path('package7b/', views.package7b, name='package7b'),
    path('package7add/', views.package7add, name='package7add'),
    path('<int:id>/deletepackage7/', views.deletepackage7, name='deletepackage7'),
    path('<int:id>/deletepackage7a/', views.deletepackage7a, name='deletepackage7a'),

    path('package8/', views.package8, name='package8'),
    path('package8a/', views.package8a, name='package8a'),
    path('package8b/', views.package8b, name='package8b'),
    path('package8add/', views.package8add, name='package8add'),
    path('<int:id>/deletepackage8/', views.deletepackage8, name='deletepackage8'),
    path('<int:id>/deletepackage8a/', views.deletepackage8a, name='deletepackage8a'),

    path('package9/', views.package9, name='package9'),
    path('package9a/', views.package9a, name='package9a'),
    path('package9b/', views.package9b, name='package9b'),
    path('package9add/', views.package9add, name='package9add'),
    path('<int:id>/deletepackage9/', views.deletepackage9, name='deletepackage9'),
    path('<int:id>/deletepackage9a/', views.deletepackage9a, name='deletepackage9a'),

    path('package10/', views.package10, name='package10'),
    path('package10a/', views.package10a, name='package10a'),
    path('package10b/', views.package10b, name='package10b'),
    path('package10add/', views.package10add, name='package10add'),
    path('<int:id>/deletepackage10/', views.deletepackage10, name='deletepackage10'),
    path('<int:id>/deletepackage10a/', views.deletepackage10a, name='deletepackage10a'),

    path('package11/', views.package11, name='package11'),
    path('package11a/', views.package11a, name='package11a'),
    path('package11b/', views.package11b, name='package11b'),
    path('package11add/', views.package11add, name='package11add'),
    path('<int:id>/deletepackage11/', views.deletepackage11, name='deletepackage11'),
    path('<int:id>/deletepackage11a/', views.deletepackage11a, name='deletepackage11a'),

    path('package12/', views.package12, name='package12'),
    path('package12a/', views.package12a, name='package12a'),
    path('package12b/', views.package12b, name='package12b'),
    path('package12add/', views.package12add, name='package12add'),
    path('<int:id>/deletepackage12/', views.deletepackage12, name='deletepackage12'),
    path('<int:id>/deletepackage12a/', views.deletepackage12a, name='deletepackage12a'),

    path('package13/', views.package13, name='package13'),
    path('package13a/', views.package13a, name='package13a'),
    path('package13b/', views.package13b, name='package13b'),
    path('package13add/', views.package13add, name='package13add'),
    path('<int:id>/deletepackage13/', views.deletepackage13, name='deletepackage13'),
    path('<int:id>/deletepackage13a/', views.deletepackage13a, name='deletepackage13a'),

    path('package14/', views.package14, name='package14'),
    path('package14a/', views.package14a, name='package14a'),
    path('package14b/', views.package14b, name='package14b'),
    path('package14add/', views.package14add, name='package14add'),
    path('<int:id>/deletepackage14/', views.deletepackage14, name='deletepackage14'),
    path('<int:id>/deletepackage14a/', views.deletepackage14a, name='deletepackage14a'),

    path('package15/', views.package15, name='package15'),
    path('package15a/', views.package15a, name='package15a'),
    path('package15b/', views.package15b, name='package15b'),
    path('package15add/', views.package15add, name='package15add'),
    path('<int:id>/deletepackage15/', views.deletepackage15, name='deletepackage15'),
    path('<int:id>/deletepackage15a/', views.deletepackage15a, name='deletepackage15a'),

    path('package16/', views.package16, name='package16'),
    path('package16a/', views.package16a, name='package16a'),
    path('package16b/', views.package16b, name='package16b'),
    path('package16add/', views.package16add, name='package16add'),
    path('<int:id>/deletepackage16/', views.deletepackage16, name='deletepackage16'),
    path('<int:id>/deletepackage16a/', views.deletepackage16a, name='deletepackage16a'),

    path('packagenamechange/', views.packagenamechange, name='packagenamechange'),
    path('reviewpackages/', views.reviewpackages, name='reviewpackages'),

    path('<int:id>/changename1/', views.changename1, name='changename1'),
    path('<int:id>/acceptchangename1/', views.acceptchangename1, name='acceptchangename1'),
    path('<int:id>/changename2/', views.changename2, name='changename2'),
    path('<int:id>/acceptchangename2/', views.acceptchangename2, name='acceptchangename2'),
    path('<int:id>/changename3/', views.changename3, name='changename3'),
    path('<int:id>/acceptchangename3/', views.acceptchangename3, name='acceptchangename3'),
    path('<int:id>/changename4/', views.changename4, name='changename4'),
    path('<int:id>/acceptchangename4/', views.acceptchangename4, name='acceptchangename4'),
    path('<int:id>/changename5/', views.changename5, name='changename5'),
    path('<int:id>/acceptchangename5/', views.acceptchangename5, name='acceptchangename5'),
    path('<int:id>/changename6/', views.changename6, name='changename6'),
    path('<int:id>/acceptchangename6/', views.acceptchangename6, name='acceptchangename6'),
    path('<int:id>/changename7/', views.changename7, name='changename7'),
    path('<int:id>/acceptchangename7/', views.acceptchangename7, name='acceptchangename7'),
    path('<int:id>/changename8/', views.changename8, name='changename8'),
    path('<int:id>/acceptchangename8/', views.acceptchangename8, name='acceptchangename8'),
    path('<int:id>/changename9/', views.changename9, name='changename9'),
    path('<int:id>/acceptchangename9/', views.acceptchangename9, name='acceptchangename9'),
    path('<int:id>/changename10/', views.changename10, name='changename10'),
    path('<int:id>/acceptchangename10/', views.acceptchangename10, name='acceptchangename10'),
    path('<int:id>/changename11/', views.changename11, name='changename11'),
    path('<int:id>/acceptchangename11/', views.acceptchangename11, name='acceptchangename11'),
    path('<int:id>/changename12/', views.changename12, name='changename12'),
    path('<int:id>/acceptchangename12/', views.acceptchangename12, name='acceptchangename12'),
    path('<int:id>/changename13/', views.changename13, name='changename13'),
    path('<int:id>/acceptchangename13/', views.acceptchangename13, name='acceptchangename13'),
    path('<int:id>/changename14/', views.changename14, name='changename14'),
    path('<int:id>/acceptchangename14/', views.acceptchangename14, name='acceptchangename14'),
    path('<int:id>/changename15/', views.changename15, name='changename15'),
    path('<int:id>/acceptchangename15/', views.acceptchangename15, name='acceptchangename15'),
    path('<int:id>/changename16/', views.changename16, name='changename16'),
    path('<int:id>/acceptchangename16/', views.acceptchangename16, name='acceptchangename16'),

    path('<int:jobid>/print/', views.print, name='print'),
    path('<int:bidid>/contract/', views.contract, name='contract'),
    path('<int:bidid>/contractA/', views.contractA, name='contractA'),
    path('<int:bidid>/contractB/', views.contractB, name='contractB'),
    path('<int:bidid>/contractC/', views.contractC, name='contractC'),
    path('<int:bidid>/contractD/', views.contractD, name='contractD'),
    path('<int:bidid>/contractE/', views.contractE, name='contractE'),
    path('<int:jobid>/contractmulti/', views.contractmulti, name='contractmulti'),
    path('<int:jobid>/memo31/', views.memo31, name='memo31'),
    path('<int:jobid>/memo1/', views.memo1, name='memo1'),
    path('<int:jobid>/memo2/', views.memo2, name='memo2'),
    path('<int:jobid>/memo3/', views.memo3, name='memo3'),
    path('<int:jobid>/memo4/', views.memo4, name='memo4'),
    path('<int:jobid>/memo5/', views.memo5, name='memo5'),
    path('<int:jobid>/memo6/', views.memo6, name='memo6'),
    path('<int:jobid>/memo7/', views.memo7, name='memo7'),
    path('<int:jobid>/memo8/', views.memo8, name='memo8'),
    path('<int:jobid>/memo9/', views.memo9, name='memo9'),
    path('<int:jobid>/memo10/', views.memo10, name='memo10'),
    path('<int:jobid>/memo11/', views.memo11, name='memo11'),
    path('<int:jobid>/memo12/', views.memo12, name='memo12'),
    path('<int:jobid>/memo13/', views.memo13, name='memo13'),
    path('<int:jobid>/memo14/', views.memo14, name='memo14'),
    path('<int:jobid>/memo15/', views.memo15, name='memo15'),
    path('<int:jobid>/memo16/', views.memo16, name='memo16'),
    path('<int:jobid>/memo17/', views.memo17, name='memo17'),
    path('<int:jobid>/memo18/', views.memo18, name='memo18'),

    path('custpageloc', views.custpageloc, name='custpageloc'),
    path('multiformb', views.multiformb, name='multiformb'),

    path('<int:bidid>/targetnetprofit/', views.targetnetprofit, name='targetnetprofit'),
    path('<int:bidid>/netprofit/', views.netprofit, name='netprofit'),
    path('<int:bidid>/load_netprofit/', views.load_netprofit, name='load_netprofit'),
    path('<int:bidid>/load_costplusprofit/', views.load_costplusprofit, name='load_costplusprofit'),
    path('<int:bidid>/load_totalsubcost/', views.load_totalsubcost, name='load_totalsubcost'),
    path('<int:bidid>/load_finaljobcost/', views.load_finaljobcost, name='load_finaljobcost'),


]